name: Publish CRX

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish Chrome Extension
    runs-on: ubuntu-latest
    environment: chrome-extension-upload
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-node@v4.4.0
      with:
        node-version: 22
    - name: Prepare
      run: echo "${{ secrets.PEM }}" > key.pem
    - name: Build
      run: google-chrome-stable --pack-extension=./src --pack-extension-key=key.pem
    - name: Check
      run: ls -la
    - name: Upload
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: src.crx
        extension-id: conemkapghgifleljonppmkekbfeckko
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
        publish: true
    - name: Clean up
      run: rm key.pem
