name: Publish ZIP (Test)

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish Chrome Extension (Test)
    runs-on: ubuntu-latest
    environment: chrome-extension-upload
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-node@v4.4.0
      with:
        node-version: 22
    - name: Build
      run: |
        mkdir -p dist
        zip -r dist/nnn.zip . -x "*.git*" "dist/*" "node_modules/*" "demo/*.png" "examples/*"
    - name: Upload & Release
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: dist/nnn.zip
        extension-id: conemkapghgifleljonppmkekbfeckko
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
        publish: false
