name: Test Alternative

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish Chrome Extension (Alternative)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-node@v4.4.0
      with:
        node-version: 22
    - name: Build
      run: |
        mkdir -p dist
        zip -r dist/nnn.zip . -x "*.git*" "dist/*" "node_modules/*" "demo/*.png" "examples/*"
    - name: Upload & Release (Alternative Action)
      uses: mobilefirstllc/cws-publish@latest
      with:
        action: 'upload'
        client_id: ${{ secrets.CLIENT_ID }}
        client_secret: ${{ secrets.CLIENT_SECRET }}
        refresh_token: ${{ secrets.REFRESH_TOKEN }}
        extension_id: 'conemkapghgifleljonppmkekbfeckko'
        zip_file: 'dist/nnn.zip' 